config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :users
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :picture, optional: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, presence: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, ImageUploader
  def user
    return User.find_by(id: self.user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }
  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  def pictures
    return Picture.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
  @contact = Contact.new(contact_params)
  if @contact.save
    ContactMailer.contact_mail(@contact).deliver  ##追記
    redirect_to contacts_path, notice: 'Contact was successfully created.'
  else
    render :new
  end
end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end

  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
    @picture = Picture.find_by(id: params[:id])
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    @picture = Picture.find_by(id: params[:id])
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    if params[:back]
      render :new
    else
    @picture = current_user.pictures.build(picture_params)
      if @picture.save
        redirect_to pictures_path, notice: "投稿しました！"
      else
        render 'new'
      end
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: '更新しました！' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '削除しました！' }
    end
  end

  helper_method :current_user, :created_by?

  private

  def set_picture
  @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :content, :image_cache)
  end

  def authenticate_user
    if current_user != @picture.user
      flash[:notice] = "あなたの投稿では無いので操作できません"
      redirect_to pictures_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: @user.id)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'ユーザー情報を削除しました。' }
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
  params.require(:user).permit(:name, :email, :content, :password, :image,
                               :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
  current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/favorites/index.html.erb
<div class="favorite-section">
  <h1>お気に入り一覧</h1>
  <% @favorites.each do |favorite| %>
  <%= image_tag "#{favorite.picture.image}", :size =>'150x150' %>
  <% end %>
</div>

<div class="link-block">
<%= link_to '戻る', user_path(current_user.id), :style=>"font-size:32px; font-weight:bold;" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>



  <body>
<header>
  <div class="header-left">
    <i  class="fas fa-camera-retro fa-3x"></i>
    <h1><%= link_to 'イクラスタグラム', pictures_path, :style=>"" %></h1>
  </div>

</header>
<div class="main-wrapper">

    <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </div>
    <footer>
      <p>© 2019 TANIZAWA CORPORATION.(Test Application)</p>
    </footer>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %></h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <div class="field-content">
      <%= form.file_field :image %>
      </div>
    <%= form.hidden_field :image_cache %>
    <strong>コメント</strong>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <p>タイトル:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>

  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<div class="edit-section">
<h1>編集画面</h1>

<%= render 'form', picture: @picture %>

<div class="link-block">
<%= link_to '詳細画面へ', @picture, :style=>"font-size:32px; font-weight:bold;" %> |
<%= link_to '戻る', pictures_path, :style=>"font-size:32px; font-weight:bold;" %>
</div>
</div>

app/views/pictures/index.html.erb
  <div class="btn-content">
    <button type="button" class="btn btn-warning btn-md">
      <%= link_to "新規投稿", new_picture_path, :style=>"color:white;"%>
    </button>
    <button type="button" class="btn btn-success btn-md">
      <%= link_to "Mypage", user_path(current_user.id), :style=>"color:white;" %>
    </button>
    <% if logged_in? %>
    <button type="button" class="btn btn-danger btn-md">
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete , :style=>"color:white;"%>
      <% else %>
    <button type="button" class="btn btn-primary btn-md">
      <%= link_to "新規登録", new_user_path, :style=>"color:white;" %>
    </button>
    <button type="button" class="btn btn-secondary btn-md">
      <%= link_to "ログイン", new_session_path, :style=>"color:white;" %>
    </button>
    <% end %>
  </div>
    <h1>◆New Pictures◆</h1>
    <div class="images">
        <% @pictures.each do |picture| %>
        <div class="image-content">
        <div class="image-icon">
          <i><%= image_tag "#{picture.image}", :size =>'350x350' %></i>
          </div>
          <button type="button" class="btn btn-primary btn-md">
            <%= link_to '詳細', picture , :style=>"color:white;"%>
          </button>
      <% if current_user.id == picture.user.id %>
          <button type="button" class="btn btn-success btn-md">
            <%= link_to '編集', edit_picture_path(picture), :style=>"color:white;" %>
          </button>
          <button type="button" class="btn btn-danger btn-md">
            <%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除しますか？' }, :style=>"color:white;" %>
          </button>
            </div>
          </div>
      <% end %>
    <% end %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

<div class="link-block">
<%= link_to '戻る', pictures_path, :style=>"font-size:32px; font-weight:bold;" %>
</div>

app/views/pictures/show.html.erb
<div class="title-text">
<strong>◆コメント◆<br><%= @picture.content %></strong>
</div>

<i>
<%= image_tag "#{@picture.image}", :size =>'300x300' %>
</i>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
  <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
  <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %></h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
  </div>

  <div class="field">
    <%= form.label :コメント %>
    <%= form.text_area :content %>
  </div>

  <div class="field-content">
    <%= form.label :アイコン %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>アカウント情報編集</h1>
<i><%= image_tag "#{@user.image}", :size =>'150x150' %></i>

<%= render 'form', user: @user %>

<div class="link-block">
<%= link_to '戻る', @user, :style=>"font-size:32px; font-weight:bold;" %> |
</div>

app/views/users/index.html.erb
<h1>登録完了アカウント</h1>

<table align="center" style="font-size:24px">
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <button type="button" class="btn btn-success btn-md">
          <%= link_to '編集', edit_user_path(user), :style=>"color:white;" %>
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-danger btn-md">
          <%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除しますか?' }, :style=>"color:white;" %>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="link-block">
<%= link_to 'ホーム画面へ', pictures_path, :style=>"font-size:24px;" %><br>
<%= link_to '新規アカウント登録画面へ', new_user_path, :style=>"font-size:24px;" %>
</div>

app/views/users/new.html.erb
<h1>新規アカウント登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %></h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>

  <%= form_with(model: @user, local: true) do |f| %>
  <div class="form-text">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="form-text">
  <%= f.label :email %>
  <%= f.email_field :email %>
  </div>
  <div class="form-text">
  <%= f.label :コメント %>
  <%= f.text_area :content %>
  </div>
  <div class="field-content">
  <%= f.label :アイコン %>
  <%= f.file_field :image %>
  </div>
  <div class="form-text">
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>
  <div class="form-text">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </div>
  <div class="submit-button">
  <%= f.submit "アカウント登録" %>

  </div>
</div>

<% end %>

app/views/users/show.html.erb
<div class="user-wrapper">
  <div class="user-information">
    <i><%= image_tag "#{@user.image}", :size =>'250x250' %></i>
    <h1><%= @user.name %></h1>
    <p>メールアドレス: <%= @user.email %></p>
    <p>コメント: <%= @user.content %></p>
    <button type="button" class="btn btn-success btn-md">
      <%= link_to 'プロフィールを編集', edit_user_path(current_user.id), :style=>"color:white;" %>
    </button>
    <button type="button" class="btn btn-success btn-md">
      <%= link_to 'お気に入り', favorites_path(current_user.id), :style=>"color:white;" %>
    </button>

    <div>
    </div>
</div>